# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD 2-Clause License

# Base image
FROM python:3.12-slim

# Image metadata
LABEL maintainer="NVIDIA"
LABEL description="Voice Agent example for Agentic Patient Front Desk Assistant"
LABEL version="1.0"

# Environment setup
ENV PYTHONUNBUFFERED=1

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglx-mesa0 \
    curl \
    ffmpeg \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir --upgrade pip uv

# clone the ace-controller repository 
WORKDIR /
RUN git clone https://github.com/NVIDIA/ace-controller.git -b develop-health

# App directory setup
WORKDIR /ace-controller

# App files
COPY ./ ./examples/healthcare_agent/

# Example app directory
WORKDIR /ace-controller/examples/healthcare_agent

# Dependencies
RUN uv sync --frozen

# Port configuration
EXPOSE 7860

# Start command
CMD ["uv", "run", "pipeline-patient.py"]
