apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambient-patient.fullname" . }}-app-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ambient-patient.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-server
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.appServer.port }}
    targetPort: {{ .Values.service.appServer.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "ambient-patient.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-server
